config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  root "pages#index"

  get "simple", to: "pages#simple"
  get "no-router", to: "pages#no_router"

  # React Router needs a wildcard
  get "react-router(/*all)", to: "pages#index"

  resources :comments
  mount ActionCable.server => "/cable"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author, :text, presence: true
  after_commit { CommentRelayJob.perform_later(self) }
end

app/models/git_commit_sha.rb
# Retrieves the current git commit SHA of the project
class GitCommitSha
  def self.current_sha
    @sha ||= retrieve_sha_from_file.presence || retrieve_sha_from_git
  end

  def self.current_sha=(sha)
    @sha = sha
  end

  def self.reset_current_sha
    self.current_sha = nil
  end

  # Assumes the git CLI is available. This is not the case in production on Heroku.
  def self.retrieve_sha_from_git
    `git rev-parse HEAD 2>/dev/null`.to_s.strip
  end

  # Assumes a .source_version file with SHA inside. A special Heroku buildpack creates this for us in production.
  def self.retrieve_sha_from_file
    expected_filepath = Rails.root.join(".source_version")
    File.exist?(expected_filepath) ? File.read(expected_filepath).to_s.strip : nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception,
                       if: proc { request.headers["X-Auth"] != "tutorial_secret" }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all.order("id DESC")
  end

  # GET /comments/1
  # GET /comments/1.json
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:author, :text)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include ReactOnRails::Controller
  before_action :set_comments

  def index
    # NOTE: The below notes apply if you want to set the value of the props in the controller, as
    # compared to the view. However, it's more convenient to use Jbuilder from the view. See
    # app/views/pages/index.html.erb:20
    #
    #  <%= react_component('App', props: render(template: "/comments/index.json.jbuilder"),
    #     prerender: true) %>
    #
    #
    # NOTE: this could be an alternate syntax if you wanted to pass comments as a variable to a partial
    # @comments_json_sting = render_to_string(partial: "/comments/comments.json.jbuilder",
    #                                         locals: { comments: Comment.all }, format: :json)
    # NOTE: @comments is used by the render_to_string call
    # @comments_json_string = render_to_string("/comments/index.json.jbuilder")
    # NOTE: It's CRITICAL to call respond_to after calling render_to_string, or else Rails will
    # not render the HTML version of the index page properly. (not a problem if you do this in the view)
    # respond_to do |format|
    #   format.html
    # end

    redux_store("routerCommentsStore", props: comments_json_string)
    render_html
  end

  # Declaring no_router and simple to indicate we have views for them
  def no_router
    redux_store("commentsStore", props: comments_json_string)
    render_html
  end

  def simple; end

  private

  def set_comments
    @comments = Comment.all.order("id DESC")
  end

  def comments_json_string
    render_to_string(template: "/comments/index.json.jbuilder",
                     locals: { comments: Comment.all }, format: :json)
  end

  def render_html
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def git_commit_sha
    GitCommitSha.current_sha
  end

  def git_commit_sha_short
    full_sha = git_commit_sha
    full_sha[-7..-1]
  end
end

app/views/comments/_form.html.haml
= form_for(@comment) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - @comment.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :author, 'Your Name'
    %br/
    = f.text_field :author
  .field
    = f.label :text, 'Say something using markdown...'
    %br/
    = f.text_area :text
  .actions
    = f.submit 'Post'

app/views/comments/edit.html.haml
%h1 Editing Comment
= render 'form'
= link_to 'Show', @comment
|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Using Classic Rails 4.2 "generate scaffold"
%hr/
%p#notice= notice
%h2 Listing Comments
%table
  %thead
    %tr
      %th Author
      %th Text
      %th{:colspan => "3"}
  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.author
        %td= comment.text
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New Comment
= render 'form'
= link_to 'Back', comments_path

app/views/comments/show.html.haml
.comment
  %p#notice= notice
  %p.js-comment-author
    %strong Author:
    = @comment.author
  %p.js-comment-text
    %strong Text:
    = @comment.text
= link_to 'Edit', edit_comment_path(@comment)
|
= link_to 'Back', comments_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsReactTutorial
    = env_stylesheet_link_tag(static: 'application_static', |
      hot: 'application_non_webpack',                       |
      media: 'all',                                         |
      'data-turbolinks-track' => "reload")                  |
    / These do not use turbolinks, so no data-turbolinks-track
    / This is to load the hot assets.
    = env_javascript_include_tag(hot: ['http://localhost:3500/vendor-bundle.js', |
      'http://localhost:3500/app-bundle.js'])                                    |
    / These do use turbolinks
    = env_javascript_include_tag(static: 'application_static', |
      hot: 'application_non_webpack',                          |
      'data-turbolinks-track' => "reload")                     |
    = csrf_meta_tags
  %body
    = react_component "NavigationBarApp"
    .container
      = yield
    /
      This is a placeholder for ReactOnRails to know where to render the store props for
      client side hydration
    = redux_store_hydration_data

app/views/pages/_header.html.haml
%p React
%hr/

app/views/pages/index.html.haml
%h2
  = link_to "Open Source example",                               |
    "https://github.com/shakacode/react-webpack-rails-tutorial/" |
  of using the #{link_to "React on Rails gem", "https://github.com/shakacode/react_on_rails"}
= render "header"
/ Note, pre-rendering set in /config/initializers/react_on_rails.rb
= react_component('RouterApp', id: "RouterApp-react-component-0")

app/views/pages/no_router.html.haml
%h2
  Using React (Server rendering) + Redux + Rails Backend (using the
  = succeed ")" do
    %a{:href => "https://github.com/shakacode/react_on_rails"} react_on_rails gem
= render "header"
/ Note, pre-rendering set in /config/initializers/react_on_rails.rb
= react_component('App')

app/views/pages/simple.html.haml
%h2
  Using React (no Flux framework) + Rails Backend (with
  = succeed ")" do
    %a{:href => "https://github.com/shakacode/react_on_rails"} react_on_rails gem
%p This example is much simpler than the one using React + Redux and is appropriate when:
%ul
  %li No or minimal MVC
  %li No async necessary
  %li No server rendering
  %li No pre-population of props
%hr/
/ This component is super simple! So no redux, no prerendering.
= react_component('SimpleCommentScreen', props: {}, prerender: false)